import numpy as np

RANDOM_SEED = 42
RANDOM_RNG = np.random.default_rng()

MAX_TEST = 100
MAX_VERSION = 5
MAX_RUN = 100

PROBABILITY_CLEAR = 0.2
PROBABILITY_FLAKY_LOW = 0.2
PROBABILITY_FLAKY_HIGH = 0.3
PROBABILITY_FLAKY_MIN = 0.0
PROBABILITY_FLAKY_MAX = 0.5
PROBABILITY_FLAKY_DELTA_MIN = 0.0
PROBABILITY_FLAKY_DELTA_MAX = 0.2

TREND_VERSION = 'increase_exponential'
TREND_RUN = 'increase_exponential'

OUTCOME_CLEAN = ['SUCCESSFUL', 'SKIP']
OUTCOME_CLEAN_PROBABILITY = [0.8, 0.2]

OUTCOME_FLAKY = ['FAIL', 'ERROR']
OUTCOME_FLAKY_PROBABILITY = [0.8, 0.2]

REPORT_PROBABILITY = 1

PATH_NFF = 'data/nff/test.csv'
PATH_EFS = 'data/efs/test.csv'
